apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 3m
  releaseName: istio-ingress
  values: