apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: network
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: v1.12.1
      sourceRef:
        kind: HelmRepository
        name: jetstack-chart
        namespace: flux-system
      interval: 1m
  values:
    global:
      leaderElection:
        # Override the namespace used to store the ConfigMap for leader election
        namespace: 'network'
    extraArgs:
      - --cluster-resource-namespace=network