apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: flux-system
  path: ./infrastructure/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: flux-system
  path: ./istio/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

