---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system
      interval: 10m
  releaseName: istiod