apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo-chart
      version: v6.3.6
      sourceRef:
        kind: HelmRepository
        name: podinfo-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 2