apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infrastructure/base/helm-chart-repositories/podinfo-chart.yaml
      version: 6.3.6
      sourceRef:
        kind: HelmRepository
        name: podinfo-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 2